# Generated by Django 5.1.4 on 2025-01-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UposljenaJedinica',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uposljena_jedinice', to='uposljena_jedinica.tip')),
            ],
        ),
    ]
