# Generated by Django 5.1.4 on 2025-01-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unitor', '0001_initial'),
        ('uposljena_jedinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uposljenajedinica',
            name='korisnik',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uposljene_jedinice', to='unitor.korisnik'),
            preserve_default=False,
        ),
    ]
