# Generated by Django 5.1.4 on 2025-01-12 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacije', '0001_initial'),
        ('uposljena_jedinica', '0002_uposljenajedinica_korisnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='uposljenajedinica',
            name='lokacija',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uposljene_jedinice', to='lokacije.lokacije'),
        ),
    ]
