# Generated by Django 5.1.4 on 2025-01-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0003_uposljenajedinica_lokacija'),
    ]

    operations = [
        migrations.AddField(
            model_name='uposljenajedinica',
            name='naziv',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
