# Generated by Django 5.1.4 on 2025-01-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokacije', '0001_initial'),
        ('uposljena_jedinica', '0004_uposljenajedinica_naziv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steta',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('lokacija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stete', to='lokacije.lokacije')),
                ('uposljena_jedinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stete', to='uposljena_jedinica.uposljenajedinica')),
            ],
        ),
    ]
