# Generated by Django 5.1.4 on 2025-01-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0005_steta'),
    ]

    operations = [
        migrations.AddField(
            model_name='steta',
            name='naziv',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='steta',
            name='opis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uposljenajedinica',
            name='naziv',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
