# Generated by Django 5.1.4 on 2025-01-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0006_steta_naziv_steta_opis_alter_uposljenajedinica_naziv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steta',
            name='lokacija',
        ),
    ]
