# Generated by Django 5.1.4 on 2025-01-13 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0007_remove_steta_lokacija'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetaljiIznajmljivanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznajmljena', models.BooleanField(default=False)),
                ('cijena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip_iznajmljivanja', models.CharField(choices=[('mjesecno', 'Mjesecno'), ('dnevno', 'Dnevno')], max_length=50)),
                ('iznajmljeno_od', models.DateField(blank=True, null=True)),
                ('iznajmljeno_do', models.DateField(blank=True, null=True)),
                ('jedinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalji_iznajmljivanja', to='uposljena_jedinica.uposljenajedinica')),
            ],
        ),
    ]
