# Generated by Django 5.1.4 on 2025-01-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0008_detaljiiznajmljivanja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steta',
            name='naziv',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
