# Generated by Django 5.1.4 on 2025-01-13 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0009_alter_steta_naziv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomocniRadnici',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='uposljenajedinica',
            name='pomocni_radnici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uposljena_jedinice', to='uposljena_jedinica.pomocniradnici'),
        ),
    ]
