# Generated by Django 5.1.4 on 2025-01-13 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0010_pomocniradnici_uposljenajedinica_pomocni_radnici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaljiiznajmljivanja',
            name='jedinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalji_iznajmljivanja', to='uposljena_jedinica.uposljenajedinica'),
        ),
    ]
