# Generated by Django 5.1.4 on 2025-01-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0011_alter_detaljiiznajmljivanja_jedinica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steta',
            name='uposljena_jedinica',
        ),
        migrations.AddField(
            model_name='steta',
            name='detalji_iznajmljivanja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stete', to='uposljena_jedinica.detaljiiznajmljivanja'),
            preserve_default=False,
        ),
    ]
