# Generated by Django 5.1.4 on 2025-01-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uposljena_jedinica', '0012_remove_steta_uposljena_jedinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uposljenajedinica',
            name='cijena_prednajma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
