# Generated by Django 5.1.4 on 2025-01-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unitor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steta',
        ),
    ]
