# Generated by Django 5.1.4 on 2025-01-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EksterniOglasivaci',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eksterni_oglasivaci', to='unitor.korisnik')),
            ],
        ),
    ]
