# Generated by Django 5.1.4 on 2025-01-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eksterni_oglasivaci', '0001_initial'),
        ('unitor', '0002_delete_steta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eksternioglasivaci',
            options={'verbose_name': 'Eksterni Oglasivač', 'verbose_name_plural': 'Eksterni Oglasivači'},
        ),
        migrations.AddField(
            model_name='eksternioglasivaci',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eksternioglasivaci',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eksternioglasivaci',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eksterni_oglasivaci', to='eksterni_oglasivaci.platforma'),
        ),
        migrations.AlterUniqueTogether(
            name='eksternioglasivaci',
            unique_together={('korisnik', 'platform')},
        ),
    ]
